import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>next | app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Hello Next</h1>
          <div className={styles.home}>
            {posts.slice(0, 20).map((post) => (
              <div key={post.id}>
                <h1 title="Click the button for full details">{post.title.substring(0, 10)}...</h1>
                <p title="Click the button for full details">{post.body.substring(0, 70)}...</p>
                <br />
                <Link href="/blogs/[id]" as={`/blogs/${post.id}`} legacyBehavior>
                  <a className={styles.readMoreButton}>Rad More</a>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await res.json();

  return {
    props: {
      posts,
    },
  };
}
